### ISSUE TITLE
Authentication credentials needed for league standings

### ISSUE THREAD

**Issue by lastmaj** [Flensolini/fpl-api-js#3]
Hello 
When we request a league standing, don't we need authentication credentials ? How did you solve that problem ?

**Comment by hwb15** [comment]
a GET request to the endpoint: 'https://fantasy.premierleague.com/api/leagues-classic/${LEAGUE-ID-HERE}/standings/ - will return the league standings without authentication.

Within this package - `getLeague(id)` will provide you with the json returned from the above request.

**Comment by lastmaj** [comment]
thank you for replying, I noticed that they removed this for this season, meaning that we can hit that endpoint without posting credentials. Last year I am pretty sure that URL needed auth.
